{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bagofwords.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bagofwords.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.imagePullSecret }}
imagePullSecrets:
  - name: {{ .Values.serviceAccount.imagePullSecret }}
{{- end }}
{{- end }}
